#!/usr/bin/env python3

import argparse
from io import BytesIO
from PIL import Image

import fitz
import pytesseract

parser = argparse.ArgumentParser(description='Extract contents as text from a pdf file (for use with e.g. handyoutliner)')
parser.add_argument('filename', help='a PDF-file and contents page range')
parser.add_argument('firstpage', type=int, help='start pagenumber')
parser.add_argument('lastpage', type=int, help='end pagenumber')
parser.add_argument('--o', metavar='string', default='contents.txt', type=argparse.FileType('w'))
parser.add_argument('--mag', metavar='float', default='2.0', type=float, help='optional magnification factor for better OCR')

args = parser.parse_args()

doc = fitz.open(args.filename)

mat = fitz.Matrix(args.mag, args.mag)
 
for i in range(args.firstpage - 1, args.lastpage, 1):
    print(i)
    page = doc[i]
    pix = page.getPixmap(mat)
    imdata = pix.getImageData()
    bytesim = BytesIO(imdata)
    page_string = pytesseract.image_to_string(Image.open(bytesim), config='--psm 6')
    args.o.write(page_string)
    
args.o.close()

